//
// Generated file, do not edit! Created by nedtool 5.3 from hello.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __HELLO_M_H
#define __HELLO_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0503
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>hello.msg:1</tt> by nedtool.
 * <pre>
 * packet Hello
 * {
 *     int nodes[8];
 * }
 * </pre>
 */
class Hello : public ::omnetpp::cPacket
{
  protected:
    int nodes[8];

  private:
    void copy(const Hello& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Hello&);

  public:
    Hello(const char *name=nullptr, short kind=0);
    Hello(const Hello& other);
    virtual ~Hello();
    Hello& operator=(const Hello& other);
    virtual Hello *dup() const override {return new Hello(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getNodesArraySize() const;
    virtual int getNodes(unsigned int k) const;
    virtual void setNodes(unsigned int k, int nodes);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Hello& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Hello& obj) {obj.parsimUnpack(b);}


#endif // ifndef __HELLO_M_H

